//-------------------AUTH_LOGIN-------------------//
export const AUTH_LOGIN_STARTED = "AUTH_LOGIN_STARTED";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

//-------------------AUTH_LOGOUT-------------------//
export const AUTH_LOGOUT_STARTED = "AUTH_LOGOUT_STARTED";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";

//-------------------AUTH_SIGNUP-------------------//
export const AUTH_SIGNUP_START = "AUTH_SIGNUP_START";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_FAILURE";
export const AUTH_SIGNUP_CLOSE_MODAL = "AUTH_SIGNUP_CLOSE_MODAL";
export const AUTH_SIGNUP_CLEAR_ERROR = "AUTH_SIGNUP_CLEAR_ERROR";

//-------------------AUTH_AUTHENTICATE-------------------//
export const AUTH_AUTHENTICATE = "AUTH_AUTHENTICATE";
//-------------------IS_LOGIN-------------------//
export const SET_BEARER_TOKEN = "SET_BEARER_TOKEN";

//-------------------ACCOUNT_SETTING-------------------//
export const START_LOADING_ACCOUNT_DATA = "START_LOADING_ACCOUNT_DATA";
export const SUCCESS_LOADING_ACCOUNT_DATA = "SUCCESS_LOADING_ACCOUNT_DATA";
export const FAIL_LOADING_ACCOUNT_DATA = "FAIL_LOADING_ACCOUNT_DATA";

//-------------------UPDATE_ACCOUNT_SETTING-------------------//
export const START_UPDATING_ACCOUNT_DATA = "START_UPDATING_ACCOUNT_DATA";
export const SUCCESS_UPDATING_ACCOUNT_DATA = "SUCCESS_UPDATING_ACCOUNT_DATA";
export const FAIL_UPDATING_ACCOUNT_DATA = "FAIL_UPDATING_ACCOUNT_DATA";

//-------------------UPLOAD_PHOTO-------------------//
export const START_UPLOAD_PHOTO = "START_UPLOAD_PHOTO";
export const SUCCESS_UPLOAD_PHOTO = "SUCCESS_UPLOAD_PHOTO";
export const FAIL_UPLOAD_PHOTO = "FAIL_UPLOAD_PHOTO";

//-------------------FETCH_MY_FEED-------------------//
export const START_FETCH_MY_FEED = "START_FETCH_MY_FEED";
export const SUCCESS_FETCH_MY_FEED = "SUCCESS_FETCH_MY_FEED";
export const FAIL_FETCH_MY_FEED = "FAIL_FETCH_MY_FEED";
//-------------------CREATE_NEW_FEED-------------------//
export const START_CREATE_NEW_FEED = "START_CREATE_NEW_FEED";
export const SUCCESS_CREATE_NEW_FEED = "SUCCESS_CREATE_NEW_FEED";
export const FAIL_CREATE_NEW_FEED = "FAIL_CREATE_NEW_FEED";

//-------------------MODAL-------------------//
export const OPEN_MODAL_IN_FRIENDS = "OPEN_MODAL_IN_FRIENDS";
export const CLOSE_MODAL_IN_FRIENDS = "CLOSE_MODAL_IN_FRIENDS";
export const OPEN_MODAL_IN_PROFILE = "OPEN_MODAL_IN_PROFILE";
export const CLOSE_MODAL_IN_PROFILE = "CLOSE_MODAL_IN_PROFILE";
export const ADD_DATA_IN_PROFILE_MODAL = "ADD_DATA_IN_PROFILE_MODAL";

